### ISSUE TITLE
Relacy fails to yield a possible execution in IRIW example

### ISSUE THREAD

**Issue by dvyukov** [dvyukov/relacy#1]
See the following test:
https://github.com/dvyukov/relacy/blob/master/test/iriw.cpp
The assert should fire eventually. However relacy fails to yield such execution.

**Comment by davidtgoldblatt** [comment]
Thanks to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0668r4.html, the assert ought not fire in C++20.

I've heard of 1-character fixes before, but I hadn't previously seen a 0-character one.

**Comment by dvyukov** [comment]
Ha! Pity not all problems resolve themselves if you just wait long enough.
I think I will close this then. Unlikely anybody will work on this anyway, and it it will stay in the archives for history purposes.
