### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by apoydence** [dvyukov/relacy#4]
Under supported platforms, it lists:

GCC 3.4 and above, Linux, 32-bit

Are there plans to support 64 bit?

**Comment by dvyukov** [comment]
As far as I remember it works on 64 bit.
If it doesn't, then how does it fail?

**Comment by apoydence** [comment]
I haven't seen it fail. I was just reading the docs provided on your website and wanted to ensure the integrity of the results.

**Comment by Kamayuq** [comment]
there is a compiler error about a pointer trunctation (MSVC) in some GC define block.
